title: 'Jacob Aronoff'
description: 'I program mainly in Swift, Python, and Go. I''m interested in programming with distributed technologies and have experience with Kafka, Cassandra, and ElasticSearch.'
bio: 'I''m a software engineer at Datadog. I am currently attending Northeastern University College of Computer and Information Science. I previously went to Milton Academy where I founded the school''s programming club which does programming community outreach. HackNY Class of 2017, HackNY Mentor 2018, Interact Fellow 2018'
baseurl: ""
url: 'http://jaronoff.com'
username: jaronoff97
user_title: 'Jacob Aronoff - Backend'
email: jacobaronoff45@gmail.com
twitter_username: get_sw1fty
github_username: jaronoff97
facebook_username: Jearonoff
linkedin_username: jaronoff97
disqus_username: jaronoff97
markdown: kramdown
highlighter: rouge
permalink: '/:title/'
compress_html:
    clippings: all
    comments: all
    endings: []
    profile: false
links:
    - {title: home, url: /}
    - {title: 'my posts', url: /posts}
    - {title: series, url: /series}
    - {title: tags, url: /tags}
    - {title: 'about me', url: /about}
projects:
    - {name: jaronoff97.github.io, url: 'https://github.com/jaronoff97/jaronoff97.github.io', updated: '2018-07-23T02:56:20Z', description: null}
    - {name: jsonresume-theme-onepage, url: 'https://github.com/jaronoff97/jsonresume-theme-onepage', updated: '2018-05-26T17:19:02Z', description: 'A compact theme for JSON Resume, designed for printing.'}
    - {name: .scripts, url: 'https://github.com/jaronoff97/.scripts', updated: '2018-05-12T20:09:12Z', description: ':scroll: Random scripts I''ve accumulated over the years'}
    - {name: icouldeat, url: 'https://github.com/jaronoff97/icouldeat', updated: '2018-05-07T03:17:09Z', description: 'this is the repo for my food journal. I''m going to be using it to keep track of everywhere I go in NYC and beyond!'}
    - {name: MovieMarathonTracker, url: 'https://github.com/jaronoff97/MovieMarathonTracker', updated: '2018-04-19T05:00:01Z', description: 'This repository is meant to track watching for any movie/ tv marathon. I''m going to be using it for tracking my MCU content usage.'}
    - {name: DS4400FinalProject, url: 'https://github.com/jaronoff97/DS4400FinalProject', updated: '2017-12-01T20:50:24Z', description: null}
    - {name: Feedshare-Public, url: 'https://github.com/jaronoff97/Feedshare-Public', updated: '2017-10-23T04:46:35Z', description: 'This is a public version of Feedshare with redacted keys; there is no git history so as to keep things anonymous.'}
    - {name: listmkr, url: 'https://github.com/jaronoff97/listmkr', updated: '2017-10-11T01:14:40Z', description: 'This is the public repository for the listmkr application, the code started from https://github.com/mklinga/zen-example.git'}
    - {name: mlh-api, url: 'https://github.com/jaronoff97/mlh-api', updated: '2017-08-27T22:30:41Z', description: 'Unofficial Major League Hacking API'}
    - {name: FirebasePlayground, url: 'https://github.com/jaronoff97/FirebasePlayground', updated: '2017-08-22T19:07:48Z', description: null}
    - {name: ds-reddit-project, url: 'https://github.com/jaronoff97/ds-reddit-project', updated: '2017-04-22T04:52:15Z', description: 'this is the repository for my DS4100 class which recommends subreddits'}
    - {name: listmkr_backend, url: 'https://github.com/jaronoff97/listmkr_backend', updated: '2017-01-21T07:22:59Z', description: 'This is the backend for my PennApps XV project'}
    - {name: mirrorpi, url: 'https://github.com/jaronoff97/mirrorpi', updated: '2016-12-30T02:21:58Z', description: 'This was my senior project for my last year at Milton Academy. The project was programming in python, using opencv. Check Final_Version for the code that was used in production'}
    - {name: CoffeeForChange, url: 'https://github.com/jaronoff97/CoffeeForChange', updated: '2016-12-30T02:06:26Z', description: null}
    - {name: dankWeather, url: 'https://github.com/jaronoff97/dankWeather', updated: '2016-10-26T21:02:12Z', description: null}
    - {name: AlwaysBlue, url: 'https://github.com/jaronoff97/AlwaysBlue', updated: '2016-10-01T16:12:05Z', description: 'ALWAYS BLUE ALWAYS BLUE ALWAYS BLUE ALWAYS BLUE ALWAYS BLUE '}
    - {name: hacks.github.io, url: 'https://github.com/jaronoff97/hacks.github.io', updated: '2016-09-09T00:18:07Z', description: 'The website for NU Hacks, a weekly social event for hackers and makers'}
    - {name: Flask-Boilerplate, url: 'https://github.com/jaronoff97/Flask-Boilerplate', updated: '2016-05-10T18:25:06Z', description: 'My own personal Flask Boilerplate setup'}
    - {name: Eight_Queens, url: 'https://github.com/jaronoff97/Eight_Queens', updated: '2016-04-25T18:29:19Z', description: 'Solution to Eight Queens'}
    - {name: iOS_Example, url: 'https://github.com/jaronoff97/iOS_Example', updated: '2016-04-07T12:20:52Z', description: 'This is an example for iOS apps which has segues, list views, tab views, and cocoapods.'}
    - {name: file_organizer, url: 'https://github.com/jaronoff97/file_organizer', updated: '2016-02-22T18:35:09Z', description: 'This is a python file organizer'}
    - {name: Git-Draw, url: 'https://github.com/jaronoff97/Git-Draw', updated: '2016-01-18T03:59:13Z', description: 'This is a git draw repo'}
    - {name: hexo-base, url: 'https://github.com/jaronoff97/hexo-base', updated: '2016-01-16T20:18:47Z', description: null}
    - {name: GitHubTests, url: 'https://github.com/jaronoff97/GitHubTests', updated: '2015-10-16T16:00:28Z', description: 'This is a test for people to learn how to use github, we''re going to be learning how to push, pull, and branch a git repo'}
    - {name: MASitApp, url: 'https://github.com/jaronoff97/MASitApp', updated: '2015-08-14T22:30:02Z', description: 'This app connects dog walkers and teachers'}
    - {name: ConversionCalculator, url: 'https://github.com/jaronoff97/ConversionCalculator', updated: '2015-07-17T19:41:16Z', description: 'First application made in swift'}
    - {name: Calculator-Objective-C, url: 'https://github.com/jaronoff97/Calculator-Objective-C', updated: '2015-07-06T15:37:13Z', description: 'my first calculator in objective C'}
    - {name: BMRCalc_iOS, url: 'https://github.com/jaronoff97/BMRCalc_iOS', updated: '2015-07-01T18:35:43Z', description: 'This is one of my first iOS creations with objective C'}
    - {name: MusicPlayerV2, url: 'https://github.com/jaronoff97/MusicPlayerV2', updated: '2015-05-14T02:44:30Z', description: 'First push'}
    - {name: MusicPlayer, url: 'https://github.com/jaronoff97/MusicPlayer', updated: '2015-02-28T15:38:40Z', description: 'A music player I wrote in java and javafx for an exam project. this is Version 1.0'}
exclude:
    - package.json
    - src
    - node_modules
plugins:
    - jekyll-mentions
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-gist
