# Site settings
title: Jacob Aronoff
description: "I program mainly in Swift, Python, and Java. I'm currently the lead developer for the Feedshare app."
bio: "I'm a software engineer at BitSight Technologies. I am currently attending Northeastern University College of Computer and Information Science. I previously went to Milton Academy where I founded the school's programming club which does programming community outreach."
baseurl: ""
url: "http://jaronoff.com"
# User settings
username: Jacob Aronoff
user_title: Jacob Aronoff - Backend
email: jacobaronoff45@gmail.com
twitter_username: eggsandjakey
github_username:  jaronoff97
facebook_username:  Jearonoff
linkedin_username: jaronoff97
disqus_username: jaronoff97

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  - title: home
    url: /
  - title: my posts
    url: /posts
  - title: series
    url: /series
  - title: tags
    url: /tags
  - title: about me
    url: /about
# projects in header index
projects:
  - name: Feedshare
    url: https://github.com/jaronoff97/Feedshare-Public
  - name: Mirrorpi
    url: https://github.com/jaronoff97/mirrorpi
  - name: Organizr
    url: https://github.com/jaronoff97/organizr
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist